// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6wyKZskrEXNXw80ihNU1zeIgbwOVDSE',
    appId: '1:314788412035:android:aa6941ad9ec1e6afa039b6',
    messagingSenderId: '314788412035',
    projectId: 'app-edu-ifpb',
    storageBucket: 'app-edu-ifpb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfycxmFA6p-zfUl2eD-lnIk2L6xdu6M_4',
    appId: '1:314788412035:ios:6c3b2d6ea6315ebfa039b6',
    messagingSenderId: '314788412035',
    projectId: 'app-edu-ifpb',
    storageBucket: 'app-edu-ifpb.appspot.com',
    iosBundleId: 'com.example.animalGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfycxmFA6p-zfUl2eD-lnIk2L6xdu6M_4',
    appId: '1:314788412035:ios:cf8e0d1c2c54a29aa039b6',
    messagingSenderId: '314788412035',
    projectId: 'app-edu-ifpb',
    storageBucket: 'app-edu-ifpb.appspot.com',
    iosBundleId: 'com.example.animalGame.RunnerTests',
  );
}
